services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ares_db
    ports: ['5432:5432']
    volumes: -postgres_data:/var/lib/postgresql/data
  data-ingestion:
    build: ./backend/data-ingestion
    ports:
      - '8001:8001'
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
  analysis:
    build: ./backend/analysis
    ports: ['8002:8002']
    depends_on: [kafka, postgres]

volumes: postgres_data
