services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    healthcheck:
      test: ['CMD', 'kafka-topics.sh', '--list', '--bootstrap-server', 'localhost:9092']
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      zookeeper:
        condition: service_started
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ares_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    depends_on:
      - zookeeper
  data-ingestion:
    build: ./backend/data-ingestion
    ports:
      - '8001:8001'
    depends_on:
      kafka:
        condition: service_healthy
        restart: true
    environment:
      KAFKA_BROKER: kafka:9092
  analysis:
    build: ./backend/analysis
    ports:
      - '8002:8002'
    depends_on:
      kafka:
        condition: service_healthy
        restart: true
      postgres:
        condition: service_started

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - '80:80'
  #   depends_on:
  #     data-ingestion:
  #       condition: service_started
  #     analysis:
  #       condition: service_started

volumes:
  postgres_data:
