global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'analysis-service'
    static_configs:
      - targets: ['analysis:8002']

  - job_name: 'data-ingestion'
    static_configs:
      - targets: ['data-ingestion:8001']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
